{% set name = "weblogo" %}
{% set version = "3.7.9" %}
{% set license = "MIT" %}
{% set license_file = "LICENSE.txt" %}
{% set licenses = [
  "LICENSE_biopython.txt",
  "LICENSE_BSD-3-clause.txt",
  "LICENSE_CC-BY-ND-1.0.txt",
  "LICENSE_weblogo_color.py.txt",
  "LICENSE_weblogo_colorscheme.py.txt",
  "LICENSE_weblogo_data.py.txt",
  "LICENSE_weblogo_logomath.py.txt",
  "LICENSE_weblogo_matrix.py.txt",
  "LICENSE_weblogo_MIT_1.txt",
  "LICENSE_weblogo_MIT_2.txt",
  "LICENSE_weblogo_MIT_3.txt",
  "LICENSE_weblogo_MIT_4.txt",
  "LICENSE_weblogo_seq.py.txt",
  "LICENSE_weblogo_seqio.txt",
  "LICENSE_weblogo_transform.py.txt",
] %}
{% set SEP_CHAR = "/" %}  # [not win]
{% set SEP_CHAR = "\\" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/weblogo-{{ version }}.tar.gz
  sha256: 96cea46dbf1578d39507998bcd9c69eb973d88a98821970248a4b53b2ac44fb9

build:
  number: 0
  noarch: python
  entry_points:
    - weblogo = weblogo._cli:main
    - transformseq = weblogo._transformseq:main
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - python >=3.6
    - numpy
    - scipy
    - setuptools

test:
  imports:
    - weblogo
    - weblogo.seq_io
    - weblogo.seq_io._nexus
    - weblogo.utils
  commands:
    - pip check
    - weblogo --help
    - transformseq --help
  requires:
    - pip

about:
  home: https://github.com/WebLogo/weblogo
  summary: 'WebLogo3 : Sequence Logos Redrawn'
  license: MIT
  license_file:
    - LICENSE.txt
    ## Additional licenses
    {% for license in licenses %}
    - {{ "licenses" ~ SEP_CHAR ~ license }}
    {% endfor %}
  description: |
    WebLogo (https://github.com/WebLogo/weblogo) is a tool for creating sequence 
    logos from biological sequence alignments. It can be run on the command line, 
    as a standalone webserver, as a CGI webapp, or as a python library.

    The main WebLogo webserver is located at http://weblogo.threeplusone.com

    Please consult the manual for installation instructions and more information: 
    ./weblogo/htdocs/manual.html

    (Also located at http://weblogo.threeplusone.com/manual.html.)

  doc_url: http://weblogo.threeplusone.com/manual.html
  dev_url: https://github.com/WebLogo/weblogo

extra:
  recipe-maintainers:
    - sugatoray
